namespace CuteS.LexicalAnalyser.Tokens
{
    public static class TokenAttributes
    {
        public static readonly int
            Identifier      = 256,
            Int             = 257,
            Float           = 258,
            Bool            = 260,
            True            = 261,
            False           = 262,
            String          = 263,
            Import          = 264,
            Namespace       = 265,
            Class           = 266,
            Function        = 267,
            Let             = 268,
            While           = 269,
            For             = 270,
            If              = 271,
            Else            = 272,
            Return          = 273,
            AddAssign       = 274,
            SubAssign       = 275,
            DivAssign       = 276,
            MulAssign       = 277,
            ModAssign       = 278,
            RShiftAssign    = 279,
            LShiftAssign    = 280,
            BitAndAssign    = 281,
            BitOrAssign     = 282,
            XorAssign       = 283,
            BitNotAssign    = 284,
            NotEq           = 285,
            Eq              = 286,
            GreaterEq       = 287,
            LowerEq         = 288,
            Assign          = 289,
            Add             = 290,
            Sub             = 291,
            Div             = 292,
            Mul             = 293,
            Mod             = 294,
            RShift          = 295,
            LShift          = 296,
            BitOr           = 297,
            BoolOr          = 298,
            BitAnd          = 299,
            BoolAnd         = 300,
            Xor             = 301,
            BitNot          = 302,
            BoolNot         = 303,
            TypeOp          = 304,
            DotOp           = 305,
            Greater         = 306,
            Lower           = 307;
    }
}